// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJE0aqIfKbIE-KvZ-Y9bWQcmLJMBxDx4',
    appId: '1:646737958440:web:2733aeecdc354135cbc71d',
    messagingSenderId: '646737958440',
    projectId: 'e-commerce-app-b927e',
    authDomain: 'e-commerce-app-b927e.firebaseapp.com',
    storageBucket: 'e-commerce-app-b927e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYo0VyGoPYmpr5EJ87YufnzjaqM5QEFN8',
    appId: '1:646737958440:android:bec08a55d2a8cccccbc71d',
    messagingSenderId: '646737958440',
    projectId: 'e-commerce-app-b927e',
    storageBucket: 'e-commerce-app-b927e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPV_KBSJpu5J7PlYqeB8jAjwiBBxw3RA',
    appId: '1:646737958440:ios:2b33b9bcc6ba3e7dcbc71d',
    messagingSenderId: '646737958440',
    projectId: 'e-commerce-app-b927e',
    storageBucket: 'e-commerce-app-b927e.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPV_KBSJpu5J7PlYqeB8jAjwiBBxw3RA',
    appId: '1:646737958440:ios:2b33b9bcc6ba3e7dcbc71d',
    messagingSenderId: '646737958440',
    projectId: 'e-commerce-app-b927e',
    storageBucket: 'e-commerce-app-b927e.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaJE0aqIfKbIE-KvZ-Y9bWQcmLJMBxDx4',
    appId: '1:646737958440:web:89003cde3d774df1cbc71d',
    messagingSenderId: '646737958440',
    projectId: 'e-commerce-app-b927e',
    authDomain: 'e-commerce-app-b927e.firebaseapp.com',
    storageBucket: 'e-commerce-app-b927e.firebasestorage.app',
  );
}
